package paginate

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"reflect"
	"strings"
)

// CursorPage is the cursor-paginated response envelope.
type CursorPage[T any] struct {
	Data  []T         `json:"data"`
	Meta  CursorMeta  `json:"meta"`
	Links CursorLinks `json:"links"`
}

// CursorMeta contains metadata for cursor pagination.
type CursorMeta struct {
	PerPage int  `json:"per_page"`
	HasNext bool `json:"has_next"`
	HasPrev bool `json:"has_prev"`
}

// CursorLinks contains navigation links for cursor pagination.
type CursorLinks struct {
	Self string  `json:"self"`
	Next *string `json:"next"`
	Prev *string `json:"prev"`
}

// cursorToken is the opaque token stored in the cursor query param.
// Supports both single-column (backward compat) and multi-column (keyset) formats.
type cursorToken struct {
	// Multi-column keyset fields
	Columns   []string `json:"cols,omitempty"`
	Values    []any    `json:"vals,omitempty"`
	SortDirs  []string `json:"dirs,omitempty"`
	// Single-column backward compat fields
	Column string `json:"col,omitempty"`
	Value  any    `json:"val,omitempty"`
	// Pagination direction: "after" or "before"
	Direction string `json:"dir"`
}

// EncodeCursor encodes a single-column cursor into an opaque token.
// direction must be "after" (col > val) or "before" (col < val).
// For multi-column cursors generated by NewCursorPage the token is built internally.
func EncodeCursor(column string, value any, direction string) string {
	token := cursorToken{Column: column, Value: value, Direction: direction}
	b, _ := json.Marshal(token)
	return base64.URLEncoding.EncodeToString(b)
}

// DecodeCursor decodes an opaque cursor token.
// Returns column, value, direction for single-column tokens (backward compat).
// For multi-column tokens use decodeCursorMulti internally.
func DecodeCursor(token string) (column string, value any, direction string, err error) {
	ct, err := decodeToken(token)
	if err != nil {
		return "", nil, "", err
	}
	return ct.Column, ct.Value, ct.Direction, nil
}

func decodeToken(token string) (*cursorToken, error) {
	b, err := base64.URLEncoding.DecodeString(token)
	if err != nil {
		return nil, fmt.Errorf("invalid cursor token: %w", err)
	}
	var ct cursorToken
	if err := json.Unmarshal(b, &ct); err != nil {
		return nil, fmt.Errorf("invalid cursor token: %w", err)
	}
	return &ct, nil
}

func encodeTokenMulti(cols []string, vals []any, sortDirs []string, direction string) string {
	token := cursorToken{Columns: cols, Values: vals, SortDirs: sortDirs, Direction: direction}
	b, _ := json.Marshal(token)
	return base64.URLEncoding.EncodeToString(b)
}

// NewCursorPage constructs a CursorPage[T] with metadata and HATEOAS links.
//
// rawItems must contain limit+1 items fetched from the database — the extra item
// is used to detect whether a next page exists and is then discarded automatically.
//
// Sort columns and directions are derived from params automatically.
// Cursor values are extracted from the items via reflection on json tags.
//
// Example:
//
//	// repository: fetch limit+1
//	b := paginate.NewBuilder().Table("users").Model(&User{}).
//	    OrderBy("created_at", "DESC").OrderBy("id").FromStruct(params)
//	rawItems, _ := repo.fetch(b.BuildSQL())
//
//	// handler: one line
//	page := paginate.NewCursorPage(rawItems, params, r.URL)
func NewCursorPage[T any](rawItems []T, params *PaginationParams, baseURL *url.URL) CursorPage[T] {
	limit := params.Limit
	if limit <= 0 {
		limit = GetDefaultLimit()
	}

	hasNext := len(rawItems) > limit
	data := rawItems
	if hasNext {
		data = rawItems[:limit]
	}

	hasPrev := params.Cursor != ""

	meta := CursorMeta{PerPage: limit, HasNext: hasNext, HasPrev: hasPrev}
	links := CursorLinks{Self: baseURL.String()}

	cols, sortDirs := extractSortInfo(params)

	if len(cols) > 0 && len(data) > 0 {
		if hasNext {
			nextVals := extractFieldsByJSONTag(data[len(data)-1], cols)
			next := buildCursorURLMulti(baseURL, cols, nextVals, sortDirs, "after")
			links.Next = &next
		}
		if hasPrev {
			prevVals := extractFieldsByJSONTag(data[0], cols)
			prev := buildCursorURLMulti(baseURL, cols, prevVals, sortDirs, "before")
			links.Prev = &prev
		}
	}

	return CursorPage[T]{Data: data, Meta: meta, Links: links}
}

// extractSortInfo derives cursor columns and sort directions from PaginationParams.
// Supports both params.Sort ("-col" prefix for DESC) and params.SortColumns+SortDirections.
func extractSortInfo(params *PaginationParams) (columns []string, directions []string) {
	if len(params.Sort) > 0 {
		for _, s := range params.Sort {
			if strings.HasPrefix(s, "-") {
				columns = append(columns, strings.TrimPrefix(s, "-"))
				directions = append(directions, "DESC")
			} else {
				columns = append(columns, s)
				directions = append(directions, "ASC")
			}
		}
		return
	}
	if len(params.SortColumns) > 0 {
		columns = params.SortColumns
		for i := range columns {
			dir := "ASC"
			if i < len(params.SortDirections) {
				d := strings.ToUpper(params.SortDirections[i])
				if d == "DESC" {
					dir = "DESC"
				}
			}
			directions = append(directions, dir)
		}
	}
	return
}

// extractFieldsByJSONTag extracts field values from item by matching json tag names.
func extractFieldsByJSONTag[T any](item T, jsonTags []string) []any {
	vals := make([]any, len(jsonTags))
	v := reflect.ValueOf(item)
	t := reflect.TypeOf(item)
	if t.Kind() == reflect.Ptr {
		v = v.Elem()
		t = t.Elem()
	}
	for i, tag := range jsonTags {
		for j := 0; j < t.NumField(); j++ {
			fieldTag := strings.Split(t.Field(j).Tag.Get("json"), ",")[0]
			if fieldTag == tag {
				vals[i] = v.Field(j).Interface()
				break
			}
		}
	}
	return vals
}

func buildCursorURL(base *url.URL, column string, value any, direction string) string {
	u := *base
	q := u.Query()
	q.Set("cursor", EncodeCursor(column, value, direction))
	q.Del("page")
	u.RawQuery = q.Encode()
	return u.String()
}

func buildCursorURLMulti(base *url.URL, cols []string, vals []any, sortDirs []string, direction string) string {
	u := *base
	q := u.Query()
	q.Set("cursor", encodeTokenMulti(cols, vals, sortDirs, direction))
	q.Del("page")
	u.RawQuery = q.Encode()
	return u.String()
}
